//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaRRHH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AsignacionHorarios
    {
        public int AsignacionHorariosID { get; set; }
        public int EmpleadoID { get; set; }
        public int HorarioID { get; set; }
        public System.DateTime FechaAsignacion { get; set; }
        public bool Activo { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    
        public virtual Empleados Empleados { get; set; }
        public virtual Horarios Horarios { get; set; }
    }
}
