//------------------------------------------------------------------------------
// <auto-generated>
//     Este codigo se genero a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicacion.
//     Los cambios manuales en este archivo se sobrescribiran si se regenera el codigo.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaRRHH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatalogoPermisos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CatalogoPermisos()
        {
            this.Permisos = new HashSet<Permisos>();
        }
    
        public int TipoPermisoID { get; set; }
        public string NombrePermiso { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> DiasMaximos { get; set; }
        public bool Activo { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Permisos> Permisos { get; set; }
    }
}
