//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaRRHH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permisos
    {
        public int SolicitudPermisoID { get; set; }
        public int EmpleadoID { get; set; }
        public int TipoPermisoID { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public string Estado { get; set; }
        public string Observaciones { get; set; }
    
        public virtual CatalogoPermisos CatalogoPermisos { get; set; }
        public virtual Empleados Empleados { get; set; }
    }
}
