//------------------------------------------------------------------------------
// <auto-generated>
//     Este codigo se genero a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicacion.
//     Los cambios manuales en este archivo se sobrescribiran si se regenera el codigo.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaRRHH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permisos
    {
        public int SolicitudPermisoID { get; set; }
        public int EmpleadoID { get; set; }
        public int TipoPermisoID { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public string Estado { get; set; }
        public string Observaciones { get; set; }
        public bool Activo { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    
        public virtual CatalogoPermisos CatalogoPermisos { get; set; }
        public virtual Empleados Empleados { get; set; }
    }
}
