//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaRRHH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Planilla
    {
        public int PlanillaID { get; set; }
        public int EmpleadoID { get; set; }
        public int Mes { get; set; }
        public int Año { get; set; }
        public Nullable<decimal> MontoTotal { get; set; }
        public Nullable<decimal> AFP { get; set; }
        public Nullable<decimal> ISSS { get; set; }
        public Nullable<decimal> Renta { get; set; }
        public Nullable<decimal> OtrasDeducciones { get; set; }
        public string Estado { get; set; }
        public bool Activo { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    
        public virtual Empleados Empleados { get; set; }
    }
}
