//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaRRHH.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RecursosHumanosDBEntities : DbContext
    {
        public RecursosHumanosDBEntities()
            : base("name=RecursosHumanosDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AsignacionHorarios> AsignacionHorarios { get; set; }
        public virtual DbSet<Cargos> Cargos { get; set; }
        public virtual DbSet<CatalogoPermisos> CatalogoPermisos { get; set; }
        public virtual DbSet<Departamentos> Departamentos { get; set; }
        public virtual DbSet<Empleados> Empleados { get; set; }
        public virtual DbSet<Horarios> Horarios { get; set; }
        public virtual DbSet<Permisos> Permisos { get; set; }
        public virtual DbSet<Planilla> Planilla { get; set; }
        public virtual DbSet<Salarios> Salarios { get; set; }
    }
}
